#!/usr/bin/env bash
set -Eeuo pipefail
cargo build --release
repeat() {
    local count=$1
    local file=$2
    local args8=($file $file $file $file $file $file $file $file $file $file)
    local args64=("${args8[@]}" "${args8[@]}" "${args8[@]}" "${args8[@]}" "${args8[@]}" "${args8[@]}" "${args8[@]}" "${args8[@]}")
    for (( i = 0; i <= $count; i++ )); do
        cat "${args64[@]}"
    done
}
echo "Self test"
repeat 500 4-unicode.txt | pv >/dev/null
echo "Encoding Unicode"
repeat 30 4-unicode.txt | pv | taskset -c 0 ./target/release/ripmors -e standard >/dev/null
echo "Encoding ASCII"
repeat 5 1-original.txt | pv | taskset -c 0 ./target/release/ripmors -e ascii >/dev/null
echo "Decoding"
repeat 1 2-encoded.txt | pv | taskset -c 0 ./target/release/ripmors -d >/dev/null
