on:
  push:
    branches: master
  pull_request:
    branches: master

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Enable caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Rustfmt
        run: cargo fmt --check
      - name: Typos
        uses: crate-ci/typos@master
        with:
          files: src/
      - name: Clippy
        run: cargo clippy --tests
      - name: Tests
        run: cargo test
      - name: Build
        run: cargo build --verbose
      - name: Audit
        run: cargo audit -D warnings
      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
      - name: Miri
        run: cargo miri test
